# Settings to be used by various SLM / Prairie interfacing scripts
# General
save_path0: 'F:\LuSLMOnlineTest\03262024\'

# SLM
SLM_Pixels_X: 512
SLM_Pixels_Y: 512
scan_Z: -147.03 #Z device depth
ETL: -50 0 50 #Depth of Z planes reference to scan_Z

# RawDataStream
FlipEvenLines: 0

# Suite2p
nchannels: 1 #
fs: 6.9  #sampling rate for 1 Zseries
tau: 9  #sutie2p parameters
