# Settings to be used by various SLM / Prairie interfacing scripts
# General
save_path0: E:\LuSLMOnlineTest\NoAnimalTest\11202024\

# SLM
SLM_Pixels_X: 512
SLM_Pixels_Y: 512
scan_Z: 225.58 #Z device depth
ETL: -50 0 50 #Depth of Z planes reference to scan_Z
SpiralSizeUM: 15
SpiralRevolution: 3
Repetition: 8 #Pulse Number of SLM stimuli
UncagingLaserPower: 1.5 1.6 1.7 #SLM power LevelTest

# SLM Nontargets
NumNonTarget: 20 #Total Num. of NonCell-targets
NumNTperTrial: 1 #X NonCell Targets per trial
NumTrial: 1      #Total trials repeated in Single Target SLM, noted that single Target inlcuding 1 Cells and X NonCell Targets
RadiusAvoidParam: 3 #Nontargets appears outside 2x radius of targets cells
# RawDataStream
# FlipEvenLines: 0

# Suite2p
nchannels: 1 #
fs: 6.9  #sampling rate for 1 Zseries
tau: 1.3  #suite2p parameters