# Settings to be used by various SLM / Prairie interfacing scripts
# General
save_path0: E:\LuSLMOnlineTest\SL0840-Ai203\02242025\

# SLM
SLM_Pixels_X: 512
SLM_Pixels_Y: 512
scan_Z: 171.74 #Z device depth
ETL: -50 0 50 #Depth of Z planes reference to scan_Z
IsSpiral: True #whether using spiral stimulation
SpiralSizeUM: 15
SpiralRevolution: 3
Repetition: 5 #SLM pulse numbers
Duration: 20 #Duration of SLM pulse
InterPointDelay: 30 #Interval between SLM pulses
UncagingLaserPower: 1.45 1.55 1.65 #SLM power LevelTest
InitialDelay: 22.1 #SLM Initial Delay


# SLM Nontargets
NumNonTarget: 20 #Total Num. of NonCell-targets
NumNTperTrial: 9 #X NonCell Targets per trial
NumTrial: 5      #Total trials repeated in Single Target SLM, noted that single Target inlcuding 1 Cells and X NonCell Targets
RadiusAvoidParam: 3 #Nontargets appears outside 2x radius of targets cells
# RawDataStream
# FlipEvenLines: 0

# Suite2p
nchannels: 1 #
fs: 6.9  #sampling rate for 1 Zseries
tau: 0.9  #suite2p parameters


# SLM Power customarization
Ziteration: 11      # NumTrialTseries-1 trials repeated in Single Tseries; As the 1st Zseries is not synchornized with MP. So Actual trials Need to substract 1;
ZRepetition: 34      # number of repetition in each Zseries
