# Settings to be used by various SLM / Prairie interfacing scripts

# SLM
TransformFile: 20180723_2DSLMTransform_1X_Nikon16X_ETL0.mat
TransformFile3D: 3DTransform_20181017_1617.mat
SLM_Pixels_X: 512
SLM_Pixels_Y: 512
SLM_BitDepth: 8
ZeroOrderBlockSize_PX: 35  # was 45, 35 quick hack
HologramLibraryName: GenerateHologramCUDA  #was 8
AutoAdjustWeights: 1  #true
WeightingFile: 20170524_Satsuma_Leica25x_Weights_MaxCoord128.mat
SteepnessFudgeFactor: 1  # increase steepness of weighting function

# Galvo positions (GPLMaker)
ScanAmp_X: -2.085852 2.085852  # left,right - save a grid gpl -2.0859 2.0859
ScanAmp_Y: -2.332365 2.302270  # top,bottom - save a grid gpl -2.3248 2.3098
scan_Z: 249.95 #added by Hari
FOVsize_OpticalZoom: 1
FOVsize_PX: 512
FOVsize_UM_1x: 1115.5

# Mark points (XMLMaker)
LaserName: Satsuma
LaserPowerScaleFactor: 2.1
LaserPowerFile: Bruker2_PowerFile.mat  #mat file containing PV->mW fit
TriggerLine: 
VoltageOutputCategoryName: 
VoltageOutputExperimentName: 

# RawDataStream
FlipEvenLines: 0
